# Generate a working GitHub Actions workflow file for a project with all files in the root
name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - name: Build iOS App
        run: eas build --platform ios --profile production --non-interactive


