name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: choremate  # 👈 Add this if your project is inside a folder
    steps:
      - uses: actions/checkout@v3

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - run: eas build --platform ios --profile production --non-interactive

